apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: frontend-pod-failure
  namespace: sample-app
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
      - sample-app
    labelSelectors:
      app: frontend
      app.kubernetes.io/part-of: online-boutique
  duration: "30s"
